name: Build docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build proposal
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: proposal

      - name: Upload proposal PDF file
        uses: actions/upload-artifact@v4
        with:
          name: proposal
          path: proposal/main.pdf

